package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long eventId;
	private String title;
	private Long userId;
	private String description;
	private int maxRequests;
	private Long genderEventId;
	private Date dateEvent;
	private byte activeFlg;
	private Date insertDate;
	private String insertUser;
	private Date updateDate;
	private String updateUser;

	public Event() {
	}

	public Event(String title, String description, int maxRequests, Date dateEvent, byte activeFlg, Date insertDate,
			String insertUser, Date updateDate, String updateUser) {
		this.title = title;
		this.description = description;
		this.maxRequests = maxRequests;
		this.dateEvent = dateEvent;
		this.activeFlg = activeFlg;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public Event(String title, Long userId, String description, int maxRequests, Long genderEventId, Date dateEvent,
			byte activeFlg, Date insertDate, String insertUser, Date updateDate, String updateUser) {
		this.title = title;
		this.userId = userId;
		this.description = description;
		this.maxRequests = maxRequests;
		this.genderEventId = genderEventId;
		this.dateEvent = dateEvent;
		this.activeFlg = activeFlg;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public Long getEventId() {
		return this.eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getMaxRequests() {
		return this.maxRequests;
	}

	public void setMaxRequests(int maxRequests) {
		this.maxRequests = maxRequests;
	}

	public Long getGenderEventId() {
		return this.genderEventId;
	}

	public void setGenderEventId(Long genderEventId) {
		this.genderEventId = genderEventId;
	}

	public Date getDateEvent() {
		return this.dateEvent;
	}

	public void setDateEvent(Date dateEvent) {
		this.dateEvent = dateEvent;
	}

	public byte getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(byte activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
