package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

/**
 * Genderevent generated by hbm2java
 */
public class Genderevent implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer genderEventId;
	private String description;
	private byte activeFlg;

	public Genderevent() {
	}

	public Genderevent(String description, byte activeFlg) {
		this.description = description;
		this.activeFlg = activeFlg;
	}

	public Integer getGenderEventId() {
		return this.genderEventId;
	}

	public void setGenderEventId(Integer genderEventId) {
		this.genderEventId = genderEventId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(byte activeFlg) {
		this.activeFlg = activeFlg;
	}

}
