package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

/**
 * RequestId generated by hbm2java
 */
public class RequestId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private long userId;
	private int eventId;

	public RequestId() {
	}

	public RequestId(long userId, int eventId) {
		this.userId = userId;
		this.eventId = eventId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequestId))
			return false;
		RequestId castOther = (RequestId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + this.getEventId();
		return result;
	}

}
