package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

/**
 * Requeststatus generated by hbm2java
 */
public class Requeststatus implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer requestStatusId;
	private String description;
	private Byte activeFlg;

	public Requeststatus() {
	}

	public Requeststatus(String description, Byte activeFlg) {
		this.description = description;
		this.activeFlg = activeFlg;
	}

	public Integer getRequestStatusId() {
		return this.requestStatusId;
	}

	public void setRequestStatusId(Integer requestStatusId) {
		this.requestStatusId = requestStatusId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Byte getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Byte activeFlg) {
		this.activeFlg = activeFlg;
	}

}
