package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Usertofriend generated by hbm2java
 */
public class Usertofriend implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private UsertofriendId id;
	private Integer requestStatusId;
	private Date insertDate;
	private Date updateDate;
	private byte activeFlg;

	public Usertofriend() {
	}

	public Usertofriend(UsertofriendId id, Date insertDate, Date updateDate, byte activeFlg) {
		this.id = id;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
		this.activeFlg = activeFlg;
	}

	public Usertofriend(UsertofriendId id, Integer requestStatusId, Date insertDate, Date updateDate, byte activeFlg) {
		this.id = id;
		this.requestStatusId = requestStatusId;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
		this.activeFlg = activeFlg;
	}

	public UsertofriendId getId() {
		return this.id;
	}

	public void setId(UsertofriendId id) {
		this.id = id;
	}

	public Integer getRequestStatusId() {
		return this.requestStatusId;
	}

	public void setRequestStatusId(Integer requestStatusId) {
		this.requestStatusId = requestStatusId;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public byte getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(byte activeFlg) {
		this.activeFlg = activeFlg;
	}

}
