package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

/**
 * UsertofriendId generated by hbm2java
 */
public class UsertofriendId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private long userIdSender;
	private long userIdReceiver;

	public UsertofriendId() {
	}

	public UsertofriendId(long userIdSender, long userIdReceiver) {
		this.userIdSender = userIdSender;
		this.userIdReceiver = userIdReceiver;
	}

	public long getUserIdSender() {
		return this.userIdSender;
	}

	public void setUserIdSender(long userIdSender) {
		this.userIdSender = userIdSender;
	}

	public long getUserIdReceiver() {
		return this.userIdReceiver;
	}

	public void setUserIdReceiver(long userIdReceiver) {
		this.userIdReceiver = userIdReceiver;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsertofriendId))
			return false;
		UsertofriendId castOther = (UsertofriendId) other;

		return (this.getUserIdSender() == castOther.getUserIdSender())
				&& (this.getUserIdReceiver() == castOther.getUserIdReceiver());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserIdSender();
		result = 37 * result + (int) this.getUserIdReceiver();
		return result;
	}

}
