package Hibernate.Tables;

// default package
// Generated 17-gen-2019 21.26.40 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long userId;
	private String name;
	private String surname;
	private String userName;
	private String email;
	private String password;
	private String address;
	private Integer cap;
	private Byte activeFlg;
	private Date insertDate;
	private String insertUser;
	private Date updateDate;
	private String updateUser;

	public User() {
	}

	public User(String name, String surname, String email, String password, String address, String insertUser,
			String updateUser) {
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.password = password;
		this.address = address;
		this.insertUser = insertUser;
		this.updateUser = updateUser;
	}

	public User(String name, String surname, String userName, String email, String password, String address,
			Integer cap, Byte activeFlg, Date insertDate, String insertUser, Date updateDate, String updateUser) {
		this.name = name;
		this.surname = surname;
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.address = address;
		this.cap = cap;
		this.activeFlg = activeFlg;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getCap() {
		return this.cap;
	}

	public void setCap(Integer cap) {
		this.cap = cap;
	}

	public Byte getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Byte activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
